export const loginApi = 'https://iterahero.herokuapp.com/api/v1/login'
export const dashboardApi = 'https://iterahero.herokuapp.com/api/v1/dashboard'
export const greenhouseByUserId = 'https://iterahero.herokuapp.com/api/v1/greenhouse'
export const controllingApi = 'https://iterahero.herokuapp.com/api/v1/actuator?by_greenhouse_id='
export const monitoringApi = 'https://iterahero.herokuapp.com/api/v1/sensor?by_id_greenhouse='